/** Declaration file generated by dts-gen */

export function Button(_ref2: any): any;

export namespace Button {
  namespace defaultProps {
    const as: string;

    const children: any;

    const disabled: boolean;

    const id: string;

    const size: string;

    const theme: string;

    const variant: string;

    function onClick(): void;
  }
}
