import oc from "open-color";

export default {
  id: "dark",
  primaryFont: "'Fira Sans', Arial, Helvetica, sans-serif",
  secondaryFont: "'Poppins', Arial, Helvetica, sans-serif",
  backgroundColor: oc.black,
  foregroundColor: oc.white,
  primaryColor: oc.blue[4],
  primaryShade1: oc.blue[6],
  primaryShade2: oc.blue[4],
  primaryShade3: oc.blue[3],
  primaryShade4: oc.blue[2],
  primaryShade5: oc.blue[5],
  secondaryColor: oc.violet[4],
  secondaryShade1: oc.violet[6],
  secondaryShade2: oc.violet[3],
  secondaryShade3: oc.violet[2],
  secondaryShade4: oc.violet[1],
  secondaryShade5: oc.violet[5],
  accentColor: oc.cyan[4],
  accentShade1: oc.cyan[6],
  accentShade2: oc.cyan[3],
  accentShade3: oc.cyan[2],
  accentShade4: oc.cyan[1],
  accentShade5: oc.cyan[5],
  accent2Color: oc.teal[4],
  accent2Shade1: oc.teal[6],
  accent2Shade2: oc.teal[3],
  accent2Shade3: oc.teal[2],
  accent2Shade4: oc.teal[1],
  accent2Shade5: oc.teal[5],
  accent3Color: oc.red[4],
  accent3Shade1: oc.red[6],
  accent3Shade2: oc.red[3],
  accent3Shade3: oc.red[2],
  accent3Shade4: oc.red[1],
  accent3Shade5: oc.red[5],
  neutralColor: oc.gray[3],
  neutralColor1: oc.gray[3],
  neutralColor2: oc.gray[6],
  neutralColor3: oc.gray[5],
  neutralColor4: oc.gray[2],
  neutralColor5: oc.gray[4]
};
