import oc from "open-color";

export default {
  id: "light",
  primaryFont: "'Fira Sans', Arial, Helvetica, sans-serif",
  secondaryFont: "'Poppins', Arial, Helvetica, sans-serif",
  backgroundColor: oc.white,
  foregroundColor: oc.black,
  primaryColor: oc.blue[8],
  primaryShade1: oc.blue[3],
  primaryShade2: oc.blue[5],
  primaryShade3: oc.blue[6],
  primaryShade4: oc.blue[7],
  primaryShade5: oc.blue[9],
  secondaryColor: oc.violet[8],
  secondaryShade1: oc.violet[3],
  secondaryShade2: oc.violet[5],
  secondaryShade3: oc.violet[6],
  secondaryShade4: oc.violet[7],
  secondaryShade5: oc.violet[9],
  accentColor: oc.cyan[9],
  accentShade1: oc.cyan[3],
  accentShade2: oc.cyan[5],
  accentShade3: oc.cyan[6],
  accentShade4: oc.cyan[7],
  accentShade5: oc.cyan[8],
  accent2Color: oc.teal[9],
  accent2Shade1: oc.teal[3],
  accent2Shade2: oc.teal[5],
  accent2Shade3: oc.teal[6],
  accent2Shade4: oc.teal[7],
  accent2Shade5: oc.teal[8],
  accent3Color: oc.red[8],
  accent3Shade1: oc.red[3],
  accent3Shade2: oc.red[5],
  accent3Shade3: oc.red[6],
  accent3Shade4: oc.red[7],
  accent3Shade5: oc.red[9],
  neutralColor: oc.gray[7],
  neutralColor1: oc.gray[3],
  neutralColor2: oc.gray[4],
  neutralColor3: oc.gray[5],
  neutralColor4: oc.gray[6],
  neutralColor5: oc.gray[8]
};
